import type { DemoProduct, ProductFilter } from "./types";
import { EDUNA_IMAGES } from "./images";

import imgPhone from "@/assets/products/phone.jpg";
import imgAirpods from "@/assets/products/airpods.jpg";
import imgWatch from "@/assets/products/watch.jpg";
import imgSpeaker from "@/assets/products/speaker.jpg";
import imgCharger from "@/assets/products/charger.jpg";
import imgCase from "@/assets/products/case.jpg";
import imgRobot from "@/assets/products/robot.jpg";
import imgTablet from "@/assets/products/tablet.jpg";
import heroDevice from "@/assets/hero-device.jpg";

export const FILTER_TABS: { id: ProductFilter; label: string }[] = [
  { id: "all", label: "Összes" },
  { id: "phones", label: "Mobil" },
  { id: "audio", label: "Audio" },
  { id: "wearables", label: "Okosóra / tablet" },
  { id: "charging", label: "Töltő" },
];

/** Új érkezés — representative SKUs (demo árak). */
export const NEW_ARRIVALS: DemoProduct[] = [
  {
    id: "airpods4",
    brand: "Apple",
    name: "AirPods 4 (USB-C), fehér MXP63",
    price: 47990,
    old: null,
    rating: 4.9,
    tag: "Új",
    remoteSrc: EDUNA_IMAGES.apple,
    fallbackSrc: imgAirpods,
    filters: ["audio"],
    stock: "raktaron",
  },
  {
    id: "tab-s10",
    brand: "Samsung",
    name: 'Galaxy Tab S10 FE+ 13.1" Wi-Fi 8GB RAM 128GB, ezüst',
    price: 242490,
    old: null,
    rating: 4.7,
    tag: "Top",
    remoteSrc: EDUNA_IMAGES.samsung,
    fallbackSrc: imgTablet,
    filters: ["wearables"],
    stock: "raktaron",
  },
  {
    id: "cw300",
    brand: "Xiaomi",
    name: "CW300 kültéri kamera, fehér EU BHR8097EU",
    price: 15690,
    old: 18990,
    rating: 4.6,
    tag: "Akció",
    remoteSrc: EDUNA_IMAGES.xiaomi,
    fallbackSrc: imgRobot,
    filters: ["phones"],
    stock: "utolso",
  },
  {
    id: "gan-joy",
    brand: "Joyroom",
    name: "Travel Charger GaN Type-C 45W, fekete (JR-TCG13)",
    price: 4770,
    old: null,
    rating: 4.4,
    tag: "Belépő",
    remoteSrc: EDUNA_IMAGES.bannerCofidis,
    fallbackSrc: imgCharger,
    filters: ["charging"],
    stock: "raktaron",
  },
];

/** Top termékek — más válogatás, ugyanaz a kártya-komponens. */
export const TOP_PRODUCTS: DemoProduct[] = [
  {
    id: "dyson-v12",
    brand: "Dyson",
    name: "V12 Detect Slim Absolute vezeték nélküli porszívó EU 448884-01",
    price: 208290,
    old: null,
    rating: 4.8,
    tag: "Népszerű",
    remoteSrc: EDUNA_IMAGES.dyson,
    fallbackSrc: imgRobot,
    filters: ["all"],
    stock: "raktaron",
  },
  {
    id: "jbl-party",
    brand: "JBL",
    name: "Partybox Ultimate Bluetooth hangfal, fekete EU",
    price: 423990,
    old: null,
    rating: 4.9,
    tag: "Prémium",
    remoteSrc: EDUNA_IMAGES.jbl,
    fallbackSrc: imgSpeaker,
    filters: ["audio"],
    stock: "raktaron",
  },
  {
    id: "iphone16",
    brand: "Apple",
    name: "iPhone 16 Pro Max 256GB, fekete titán EU MYWV3",
    price: 451590,
    old: null,
    rating: 4.95,
    tag: "Mobil",
    remoteSrc: EDUNA_IMAGES.apple,
    fallbackSrc: imgPhone,
    filters: ["phones"],
    stock: "raktaron",
  },
  {
    id: "scooter",
    brand: "Xiaomi",
    name: "Electric Scooter 5 Pro elektromos roller, fekete EU BHR9611GL",
    price: 154090,
    old: 169990,
    rating: 4.7,
    tag: "Sport",
    remoteSrc: EDUNA_IMAGES.bannerScooter,
    fallbackSrc: heroDevice,
    filters: ["all"],
    stock: "utolso",
  },
  {
    id: "airpur",
    brand: "Xiaomi",
    name: "Smart Air Purifier 4 Compact légtisztító, fehér EU BHR5860EU",
    price: 28090,
    old: null,
    rating: 4.5,
    tag: "Otthon",
    remoteSrc: EDUNA_IMAGES.xiaomi,
    fallbackSrc: imgCase,
    filters: ["all"],
    stock: "raktaron",
  },
  {
    id: "tapo",
    brand: "TP-Link",
    name: "Tapo C520WS vezeték nélküli kültéri kamera, fehér EU",
    price: 18790,
    old: null,
    rating: 4.5,
    tag: "Okosotthon",
    remoteSrc: EDUNA_IMAGES.tplink,
    fallbackSrc: imgRobot,
    filters: ["all"],
    stock: "raktaron",
  },
];

export const ALL_DEMO_PRODUCTS: DemoProduct[] = [...NEW_ARRIVALS, ...TOP_PRODUCTS].filter(
  (p, i, arr) => arr.findIndex((x) => x.id === p.id) === i,
);

export const BRAND_LOGOS: { name: string; remote: string }[] = [
  { name: "Apple", remote: EDUNA_IMAGES.apple },
  { name: "Samsung", remote: EDUNA_IMAGES.samsung },
  { name: "JBL", remote: EDUNA_IMAGES.jbl },
  { name: "Xiaomi", remote: EDUNA_IMAGES.xiaomi },
  { name: "Dyson", remote: EDUNA_IMAGES.dyson },
  { name: "Baseus", remote: EDUNA_IMAGES.baseus },
  { name: "TP-Link", remote: EDUNA_IMAGES.tplink },
];

export const FEATURED_CATEGORY_CARDS: {
  key: string;
  label: string;
  hint: string;
  filter: ProductFilter;
  remote: string;
  fallback: string;
}[] = [
  {
    key: "audio",
    label: "Audio",
    hint: "Fejhallgató, hangszóró",
    filter: "audio",
    remote: EDUNA_IMAGES.jbl,
    fallback: imgSpeaker,
  },
  {
    key: "vac",
    label: "Porszívók",
    hint: "Robot és kézi",
    filter: "all",
    remote: EDUNA_IMAGES.dyson,
    fallback: imgRobot,
  },
  {
    key: "proj",
    label: "Projektorok",
    hint: "Házimozi",
    filter: "all",
    remote: EDUNA_IMAGES.bannerPetkit,
    fallback: heroDevice,
  },
  {
    key: "tab",
    label: "Tabletek",
    hint: "Tanulás és munka",
    filter: "wearables",
    remote: EDUNA_IMAGES.samsung,
    fallback: imgTablet,
  },
  {
    key: "mob",
    label: "Mobiltelefonok",
    hint: "Új és csomagolássérült",
    filter: "phones",
    remote: EDUNA_IMAGES.apple,
    fallback: imgPhone,
  },
  {
    key: "watch",
    label: "Okosóra",
    hint: "Wearables",
    filter: "wearables",
    remote: EDUNA_IMAGES.samsung,
    fallback: imgWatch,
  },
  {
    key: "acc",
    label: "Tartozékok",
    hint: "Tok, töltő, kábel",
    filter: "charging",
    remote: EDUNA_IMAGES.baseus,
    fallback: imgCharger,
  },
];

export const MORE_OFFERINGS: { label: string }[] = [
  { label: "Okosóra, aktivitásmérő" },
  { label: "Autófelszerelés" },
  { label: "Kamera" },
  { label: "Konyhai eszközök" },
];

export type NavItem = {
  label: string;
  slug: string;
};

export const NAV_GROUPS: {
  label: string;
  slug: string;
  items: NavItem[];
}[] = [
  {
    label: "Mobiltelefon",
    slug: "mobiltelefon",
    items: [
      { label: "Új mobiltelefon", slug: "uj-mobiltelefon" },
      { label: "Használt telefon", slug: "hasznalt-telefon" },
      { label: "Felújított telefon", slug: "felujitott-telefon" },
    ],
  },
  {
    label: "Műszaki cikk",
    slug: "muszaki-cikk",
    items: [
      { label: "Audio", slug: "audio" },
      { label: "Tablet", slug: "tablet" },
      { label: "IT termékek", slug: "it-termekek" },
      { label: "Kamera", slug: "kamera" },
      { label: "Konzol", slug: "konzol" },
      { label: "Televízió", slug: "televizio" },
    ],
  },
  {
    label: "Otthon",
    slug: "otthon",
    items: [
      { label: "Konyhai eszközök", slug: "konyhai-eszkozok" },
      { label: "Takarítás", slug: "takaritas" },
      { label: "Légtisztítás", slug: "legtisztitas" },
      { label: "Világítás", slug: "vilagitas" },
      { label: "Hűtés-fűtés", slug: "hutes-futes" },
    ],
  },
  {
    label: "Sport és szabadidő",
    slug: "sport-es-szabadido",
    items: [
      { label: "Elektromos roller", slug: "elektromos-roller" },
      { label: "Okosóra", slug: "okosora" },
      { label: "Hátizsák", slug: "hatizsak" },
    ],
  },
  {
    label: "Szépség-egészség",
    slug: "szepseg-egeszseg",
    items: [
      { label: "Borotva, hajnyíró", slug: "borotva-hajnyiro" },
      { label: "Hajszárítás", slug: "hajszaritas" },
      { label: "Fogkefe, szájápolás", slug: "fogkefe-szajapolas" },
    ],
  },
  {
    label: "Tartozék",
    slug: "tartozek",
    items: [
      { label: "Töltő", slug: "tolto" },
      { label: "Tok", slug: "tok" },
      { label: "Kábel", slug: "kabel" },
      { label: "Power bank", slug: "power-bank" },
      { label: "Üvegfólia", slug: "uvegfolia" },
    ],
  },
];

export function findCategoryBySlug(slug: string): {
  group: (typeof NAV_GROUPS)[number];
  item: NavItem;
} | null {
  for (const g of NAV_GROUPS) {
    for (const it of g.items) {
      if (it.slug === slug) return { group: g, item: it };
    }
    if (g.slug === slug) return { group: g, item: g.items[0] };
  }
  return null;
}

export const CATEGORY_DEMO_PRODUCTS: Record<string, DemoProduct[]> = {
  "uj-mobiltelefon": [
    {
      id: "iphone16pm-256-bk",
      brand: "Apple",
      name: "iPhone 16 Pro Max 256GB, fekete titán",
      price: 619990,
      old: null,
      rating: 4.95,
      tag: "Új",
      remoteSrc: EDUNA_IMAGES.apple,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fekete",
      storage: "256GB",
      ram: "8 GB",
      model: "iPhone 16 Pro Max",
    },
    {
      id: "iphone16pm-512-wh",
      brand: "Apple",
      name: "iPhone 16 Pro Max 512GB, fehér titán",
      price: 739990,
      old: null,
      rating: 4.9,
      tag: "Prémium",
      remoteSrc: EDUNA_IMAGES.apple,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fehér",
      storage: "512GB",
      ram: "8 GB",
      model: "iPhone 16 Pro Max",
    },
    {
      id: "iphone16pm-1tb-bl",
      brand: "Apple",
      name: "iPhone 16 Pro Max 1TB, sivatagi titán",
      price: 879990,
      old: null,
      rating: 4.95,
      tag: "Csúcs",
      remoteSrc: EDUNA_IMAGES.apple,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "utolso",
      color: "arany",
      storage: "1TB",
      ram: "8 GB",
      model: "iPhone 16 Pro Max",
    },
    {
      id: "iphone16-128-bl",
      brand: "Apple",
      name: "iPhone 16 128GB, kék",
      price: 399990,
      old: 419990,
      rating: 4.8,
      tag: "Akció",
      remoteSrc: EDUNA_IMAGES.apple,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "kék",
      storage: "128GB",
      ram: "8 GB",
      model: "iPhone 16",
    },
    {
      id: "iphone16-256-pk",
      brand: "Apple",
      name: "iPhone 16 256GB, rózsaszín",
      price: 449990,
      old: null,
      rating: 4.8,
      tag: "Népszerű",
      remoteSrc: EDUNA_IMAGES.apple,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "rózsaszín",
      storage: "256GB",
      ram: "8 GB",
      model: "iPhone 16",
    },
    {
      id: "galaxy-s25u-256-bk",
      brand: "Samsung",
      name: "Galaxy S25 Ultra 256GB, titánfekete",
      price: 549990,
      old: null,
      rating: 4.9,
      tag: "Új",
      remoteSrc: EDUNA_IMAGES.samsung,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fekete",
      storage: "256GB",
      ram: "12 GB",
      model: "Galaxy S25 Ultra",
    },
    {
      id: "galaxy-s25u-512-sv",
      brand: "Samsung",
      name: "Galaxy S25 Ultra 512GB, titánezüst",
      price: 639990,
      old: null,
      rating: 4.9,
      tag: "Prémium",
      remoteSrc: EDUNA_IMAGES.samsung,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "ezüst",
      storage: "512GB",
      ram: "12 GB",
      model: "Galaxy S25 Ultra",
    },
    {
      id: "galaxy-a56-128-bk",
      brand: "Samsung",
      name: "Galaxy A56 5G 128GB, fekete",
      price: 149990,
      old: null,
      rating: 4.5,
      tag: "Belépő",
      remoteSrc: EDUNA_IMAGES.samsung,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fekete",
      storage: "128GB",
      ram: "6 GB",
      model: "Galaxy A56",
    },
    {
      id: "galaxy-a56-256-bl",
      brand: "Samsung",
      name: "Galaxy A56 5G 256GB, kék",
      price: 179990,
      old: 189990,
      rating: 4.5,
      tag: "Akció",
      remoteSrc: EDUNA_IMAGES.samsung,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "kék",
      storage: "256GB",
      ram: "8 GB",
      model: "Galaxy A56",
    },
    {
      id: "galaxy-s25-256-gn",
      brand: "Samsung",
      name: "Galaxy S25 256GB, zöld",
      price: 359990,
      old: null,
      rating: 4.7,
      tag: "Top",
      remoteSrc: EDUNA_IMAGES.samsung,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "zöld",
      storage: "256GB",
      ram: "12 GB",
      model: "Galaxy S25",
    },
    {
      id: "redmi-note15p-256-bk",
      brand: "Xiaomi",
      name: "Redmi Note 15 Pro 256GB, fekete",
      price: 119990,
      old: null,
      rating: 4.6,
      tag: "Ár/érték",
      remoteSrc: EDUNA_IMAGES.xiaomi,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fekete",
      storage: "256GB",
      ram: "8 GB",
      model: "Redmi Note 15 Pro",
    },
    {
      id: "redmi-note15p-128-bl",
      brand: "Xiaomi",
      name: "Redmi Note 15 Pro 128GB, kék",
      price: 99990,
      old: 109990,
      rating: 4.5,
      tag: "Akció",
      remoteSrc: EDUNA_IMAGES.xiaomi,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "kék",
      storage: "128GB",
      ram: "6 GB",
      model: "Redmi Note 15 Pro",
    },
    {
      id: "xiaomi-15-256-wh",
      brand: "Xiaomi",
      name: "Xiaomi 15 256GB, fehér",
      price: 289990,
      old: null,
      rating: 4.7,
      tag: "Új",
      remoteSrc: EDUNA_IMAGES.xiaomi,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fehér",
      storage: "256GB",
      ram: "12 GB",
      model: "Xiaomi 15",
    },
    {
      id: "xiaomi-15-512-bk",
      brand: "Xiaomi",
      name: "Xiaomi 15 512GB, fekete",
      price: 339990,
      old: null,
      rating: 4.7,
      tag: "Prémium",
      remoteSrc: EDUNA_IMAGES.xiaomi,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "utolso",
      color: "fekete",
      storage: "512GB",
      ram: "12 GB",
      model: "Xiaomi 15",
    },
    {
      id: "honor-magic7p-512-gn",
      brand: "Honor",
      name: "Magic7 Pro 512GB, zöld",
      price: 349990,
      old: 379990,
      rating: 4.6,
      tag: "Akció",
      remoteSrc: EDUNA_IMAGES.bannerS26,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "zöld",
      storage: "512GB",
      ram: "12 GB",
      model: "Honor Magic7 Pro",
    },
    {
      id: "honor-x8b-256-sv",
      brand: "Honor",
      name: "X8b 256GB, ezüst",
      price: 79990,
      old: null,
      rating: 4.3,
      tag: "Belépő",
      remoteSrc: EDUNA_IMAGES.bannerS26,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "ezüst",
      storage: "256GB",
      ram: "4 GB",
      model: "Honor X8b",
    },
    {
      id: "moto-g85-256-lila",
      brand: "Motorola",
      name: "Moto G85 256GB, lila",
      price: 109990,
      old: null,
      rating: 4.4,
      tag: "Közép",
      remoteSrc: EDUNA_IMAGES.bannerCofidis,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "lila",
      storage: "256GB",
      ram: "8 GB",
      model: "Moto G85",
    },
    {
      id: "moto-edge50p-512-bk",
      brand: "Motorola",
      name: "Edge 50 Pro 512GB, fekete",
      price: 249990,
      old: 269990,
      rating: 4.6,
      tag: "Akció",
      remoteSrc: EDUNA_IMAGES.bannerCofidis,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fekete",
      storage: "512GB",
      ram: "12 GB",
      model: "Motorola Edge 50 Pro",
    },
    {
      id: "pixel-9-128-wh",
      brand: "Google",
      name: "Pixel 9 128GB, porcelánfehér",
      price: 329990,
      old: null,
      rating: 4.7,
      tag: "Ajánlott",
      remoteSrc: EDUNA_IMAGES.tplink,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fehér",
      storage: "128GB",
      ram: "12 GB",
      model: "Pixel 9",
    },
    {
      id: "pixel-9p-256-bk",
      brand: "Google",
      name: "Pixel 9 Pro 256GB, obsidián",
      price: 449990,
      old: null,
      rating: 4.8,
      tag: "Prémium",
      remoteSrc: EDUNA_IMAGES.tplink,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "utolso",
      color: "fekete",
      storage: "256GB",
      ram: "16 GB",
      model: "Pixel 9 Pro",
    },
    {
      id: "oneplus-13-256-bk",
      brand: "OnePlus",
      name: "OnePlus 13 256GB, fekete",
      price: 319990,
      old: null,
      rating: 4.7,
      tag: "Új",
      remoteSrc: EDUNA_IMAGES.bannerPetkit,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fekete",
      storage: "256GB",
      ram: "12 GB",
      model: "OnePlus 13",
    },
    {
      id: "oppo-reno13-256-bl",
      brand: "Oppo",
      name: "Reno13 5G 256GB, kék",
      price: 169990,
      old: null,
      rating: 4.4,
      tag: "Közép",
      remoteSrc: EDUNA_IMAGES.bannerPetkit,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "kék",
      storage: "256GB",
      ram: "8 GB",
      model: "Oppo Reno13",
    },
    {
      id: "realme-gt7p-256-or",
      brand: "Realme",
      name: "GT 7 Pro 256GB, narancssárga",
      price: 259990,
      old: 279990,
      rating: 4.6,
      tag: "Akció",
      remoteSrc: EDUNA_IMAGES.bannerScooter,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "narancssárga",
      storage: "256GB",
      ram: "12 GB",
      model: "Realme GT 7 Pro",
    },
    {
      id: "realme-c75-128-gn",
      brand: "Realme",
      name: "C75 128GB, zöld",
      price: 54990,
      old: null,
      rating: 4.2,
      tag: "Belépő",
      remoteSrc: EDUNA_IMAGES.bannerScooter,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "zöld",
      storage: "128GB",
      ram: "4 GB",
      model: "Realme C75",
    },
    {
      id: "galaxy-z-flip6-256-lila",
      brand: "Samsung",
      name: "Galaxy Z Flip6 256GB, lila",
      price: 479990,
      old: 499990,
      rating: 4.7,
      tag: "Akció",
      remoteSrc: EDUNA_IMAGES.samsung,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "nincs",
      color: "lila",
      storage: "256GB",
      ram: "12 GB",
      model: "Galaxy Z Flip6",
    },
    {
      id: "iphone16p-256-wh",
      brand: "Apple",
      name: "iPhone 16 Pro 256GB, fehér titán",
      price: 529990,
      old: null,
      rating: 4.9,
      tag: "Top",
      remoteSrc: EDUNA_IMAGES.apple,
      fallbackSrc: imgPhone,
      filters: ["phones"],
      stock: "raktaron",
      color: "fehér",
      storage: "256GB",
      ram: "8 GB",
      model: "iPhone 16 Pro",
    },
  ],
};

const CATEGORY_PRODUCTS_MAP: Record<string, DemoProduct[]> = {};

function seedCategory(slug: string, pool: DemoProduct[], count = 6): DemoProduct[] {
  if (CATEGORY_PRODUCTS_MAP[slug]) return CATEGORY_PRODUCTS_MAP[slug];
  let hash = 0;
  for (let i = 0; i < slug.length; i++) hash = ((hash << 5) - hash + slug.charCodeAt(i)) | 0;
  const shuffled = [...pool].sort((a, b) => {
    const ha = ((hash * 31 + a.id.charCodeAt(0)) | 0) & 0x7fffffff;
    const hb = ((hash * 31 + b.id.charCodeAt(0)) | 0) & 0x7fffffff;
    return ha - hb;
  });
  const result = shuffled.slice(0, Math.min(count, pool.length));
  CATEGORY_PRODUCTS_MAP[slug] = result;
  return result;
}

export function getCategoryProducts(slug: string): DemoProduct[] {
  if (CATEGORY_DEMO_PRODUCTS[slug]) return CATEGORY_DEMO_PRODUCTS[slug];
  return seedCategory(slug, ALL_DEMO_PRODUCTS, ALL_DEMO_PRODUCTS.length);
}
